repository_type: pipeline

nf_core_version: 3.5.2

lint: {}

template:
  org: nf-core
  name: dartseq
  description: Pipeline for m6A detection in RNAseq data
  author: Mathieu Flamand, Olga Brovkina, Joana Pimenta Bernardes, Fatemeh Nasehi
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features:
    - gpu
  is_nfcore: true
