lint:
  files_exist:
    - .github/workflows/linting_comment.yml
  files_unchanged:
    - .github/workflows/branch.yml
    - .github/workflows/linting.yml
  nfcore_components: false
  pipeline_todos: false
  readme: false
nf_core_version: 4.1.0
repository_type: pipeline
template:
  author: Mathieu Flamand, Olga Brovkina, Joana Pimenta Bernardes, Fatemeh Nasehi
  description: Pipeline for m6A detection in RNAseq data
  force: false
  is_nfcore: true
  name: dartseq
  org: nf-core
  outdir: .
  skip_features:
    - gpu
  version: 1.0.0dev
